### ISSUE TITLE
Linked documentation about rsyslog is out of date

### ISSUE THREAD

**Issue by allgood2386** [wodby/docs#10]
On https://github.com/wodby/docs/blob/master/docs/stacks/drupal/containers.md there is a stanza which refers to logging and rsyslog. At the end of this stanza there is a link to https://www.wellnet.it/en/blog/logging-drupal-8 which is now a dead link.

**Comment by csandanov** [comment]
Thank you, the updated link is https://www.wellnet.it/blog/logging-drupal-8
