### ISSUE TITLE
Document Solr core customization

### ISSUE THREAD

**Issue by PavelPrischepa** [wodby/docs#4]
- Stack: drupal
- Core name: `default`

Steps:
1. Remove `configSet=drupal` from `/opt/solr/server/solr/default/core.properties`
2. Copy config from _configset_ to core `cp -r /opt/solr/server/solr/configsets/drupal/conf /opt/solr/server/solr/default/`
3. Reload core from Solr dashboard or reload container to apply changes.

**Comment by csandanov** [comment]
https://wodby.com/docs/stacks/solr/#customizing-solr-core
