### ISSUE TITLE
Tab links broken on Firefox for Mac

### ISSUE THREAD

**Issue by brandonkal** [wodby/docs#6]
The top tab links (Apps, Infrastructure, etc) do not work in Firefox.

Looking at the source code, the anchor tags are being rendered, but they do not function as they are behind the `<span class="md-header-nav__topic" style="width: 715px;">` object.

The material theme does work in Firefox, so it must be something modified here or fixed later upstream. I hope this information is helpful.

**Comment by brandonkal** [comment]
The Hamburger button is also broken when visible.

**Comment by csandanov** [comment]
Wow, thank you for reporting this, we totally broke the tabs menu in FF 😰 Now fixed
